project:
  type: website

website:
  title: "BioRBard"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    highlight-style: eiffel

editor: visual



